### ISSUE TITLE
July Progress Tracker

### ISSUE THREAD

**Issue by tabcat** [hldb/welo#91]
List of things that should be included with 3.0.0

- [x] https://github.com/hldb/welo/issues/59
- [x] #95
- [x] https://github.com/hldb/welo/issues/62
- [x] #96
- [x] #97
- [x] https://github.com/hldb/welo/issues/79
- [ ] #100
- [ ] https://github.com/hldb/welo/issues/50
- [ ] https://github.com/hldb/welo/issues/78
- [ ] improved error handling
- [ ] new entry format that supports batching by default
- [ ] new pubsub replicator by @saul-jb replaces live replicator as default
- [ ] add bootstrap replicator to default replicators (maybe)
- [ ] #60
